
use_mouse = true
use_paste = false

[color_edit_zone]
bg = "#b16286"
fg = "#fbf1c7"

[color_status_bar]
bg = "#804761"
fg = "#fbf1c7"

[color_command_zone]
bg = "#9f62b1"
fg = "#fbf1c7"

[edit_keybindings]
"Esc" = "Quit"
"Up" = "MoveUp"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"Page Down" = "PageDown"
"Page Up" = "PageUp"
"Ctrls" = "SaveDocument"
"Backspace" = "DeleteCharBack"
"Del" = "DeleteCharFront"
"Ctrlp" = "GoIntoCommandMode"

[command_keybindings]
"Up" = "MoveUp"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"Page Down" = "PageDown"
"Page Up" = "PageUp"
"Backspace" = "DeleteCharBack"
"Del" = "DeleteCharFront"
"Esc" = "GoIntoEditMode"
